import type { Metadata } from "next";
import { geistSans, geistMono } from "@/src/UI/fonts/font";
import "@/src/UI/globals.css";
import { TransactionsProvider } from "../contexts/TransactionContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TransactionsProvider>
          {children}
        </TransactionsProvider>

      </body>
    </html>
  );
}
